// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDanI9EKnDnR70HAX_vFvHCBGq6-yHiwQQ',
    appId: '1:56273777475:android:475746d7e9bfbf9679f5f6',
    messagingSenderId: '56273777475',
    projectId: 'mr-notes-3c51e',
    storageBucket: 'mr-notes-3c51e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_CWj3MTXv0LP5ajXTzWZ9KNqM-RAgoBI',
    appId: '1:56273777475:ios:c3eaedd788258a4679f5f6',
    messagingSenderId: '56273777475',
    projectId: 'mr-notes-3c51e',
    storageBucket: 'mr-notes-3c51e.firebasestorage.app',
    iosBundleId: 'com.example.notePad',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA78CJLDBIwulWJsGoukXBpyb33LxaBc3I',
    appId: '1:56273777475:web:b3c2763c2e20c1df79f5f6',
    messagingSenderId: '56273777475',
    projectId: 'mr-notes-3c51e',
    authDomain: 'mr-notes-3c51e.firebaseapp.com',
    storageBucket: 'mr-notes-3c51e.firebasestorage.app',
    measurementId: 'G-B38YXQYMKE',
  );

}